# Numerical Python (Numpy)

In [3]:
import numpy as np

# Numpy Array

In [7]:
a = np.array([1,2,3])

In [35]:
a*3 #perkalian matematika menggunakan array

array([3, 6, 9])

# Math Functions

In [4]:
np.sum(3) #penjumlahan

3

In [11]:
np.mean(a) #rata-rata

2.0

In [12]:
np.sin(np.pi)

1.2246467991473532e-16

# Arange,linspace dan Logspace

In [16]:
np.arange(1,3,0.5) #array range dan bisa pakai desimal

array([1. , 1.5, 2. , 2.5])

In [21]:
np.linspace(1,10,10) #1-10 akan dipotong sebanyak 10x

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [26]:
np.logspace(-3,3,7) #mengeluarkan 10^(-3) sampai 10^(3) dengan skala logaritmik

array([1.e-03, 1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02, 1.e+03])

# Reshape 

In [34]:
a=np.array(([1,2,3,4,5,6],[7,8,9,10,11,12]))
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [38]:
a.shape

(2, 6)

In [46]:
a.reshape(4,3) #merubah jumlah baris dan kolom (-1)--> digunakan apabila datanya banyak dan numpy yg melakukannya

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [51]:
a.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# To row/to column

In [53]:
a.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [55]:
a.reshape(-1,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

# Random Number

In [64]:
np.random.rand(10)

array([0.56814818, 0.82609513, 0.34647189, 0.88984086, 0.44019797,
       0.03935992, 0.39289461, 0.92482358, 0.41233247, 0.52549519])

In [97]:
np.random.randn(10)

array([-1.05686786, -0.37153285,  1.11823461,  0.32201546, -0.15797832,
       -0.65739325,  0.842332  , -0.16033881, -0.06327167,  1.02440019])

# Controlled Randomness

In [113]:
#berfungsi untuk mengacak angka sesuai prosedur
state=np.random.RandomState(42) #yg umum dipakai adalah 42, ASCII
state.randint(2,10,10)

array([8, 5, 6, 8, 4, 9, 6, 6, 8, 3])